/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2024-12-05-5aae1d399"
#endif /* AVUTIL_FFVERSION_H */
